from .auth_routes import auth
from .user_routes import users
from .temple_routes import temples
from .master_routes import masters
from .padawan_routes import padawans
from .species_routes import species
from .lightsaber_routes import lightsabers
from .crystal_routes import crystals
from .course_routes import courses
from .enrollment_routes import enrollments
